data:
  train_split_total_pkl_file: "/data/ambience/Emotic/pkl_files/split_files/train_data_Emotic_v2_dict.pkl"
  val_split_total_pkl_file: "/data/ambience/Emotic/pkl_files/split_files/val_data_Emotic_v2_dict.pkl"
  test_split_pkl_file: "/data/ambience/Emotic/pkl_files/split_files/test_aligned_bbox_caption_data.pkl"
  base_folder: "/data/ambience/Emotic"
  train_csv_file: "/data/digbose92/emotic_experiments/context-emotion-recognition/data/train_data_Emotic_v2.csv"
  val_csv_file: "/data/digbose92/emotic_experiments/context-emotion-recognition/data/val_data_Emotic_v2.csv"
  test_csv_file: "/data/digbose92/emotic_experiments/context-emotion-recognition/data/test_aligned_bbox_caption_no_missing_data.csv"
  label_map_file: "/data/ambience/Emotic/pkl_files/emotion_mapping/discrete_emotion_mapping_Emotic.pkl"
  scene_feature_file: "/data/ambience/Emotic/pkl_files/vit_scene_feature_file/vit_scene_feature_layer_norm.pkl"
  pos_weights_file: "/data/ambience/Emotic/pkl_files/pos_weights/pos_weights.pkl"

parameters:
  batch_size: 32
  train_shuffle: True
  val_shuffle: False
  test_shuffle: False
  epochs: 20
  max_len: 512
  early_stop: 5
  clip_norm: 0.005
  num_workers: 4

transforms:
  size: 224
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

device:
  is_cuda: True 

loss:
  continuous_loss_option: 'mean_square_loss'
  discrete_loss_option: 'binary_cross_entropy_loss'
  weight_continuous_loss: 0.40
  weight_discrete_loss: 0.60
     
optimizer:
  choice: 'AdamW'
  lr: 2e-5
  weight_decay: 0.0001
  # gamma: 0.90
  # scheduler: 'exponential_scheduling'

model:
  model_type: 'caption_person_MHA_model_scene_late_fusion_AVD_discrete_train_test_val_multiple_seeds_optimal_weights'
  dim_model: 512
  dim_feedforward: 2048
  num_heads: 8
  drop_prob: 0.1
  add_bias: True 
  activation: 'relu'
  batch_first: True
  num_layers: 4
  scene_feat_dim: 768
  person_model_option: 'resnet34'
  person_max_len: 49
  text_max_len: 512
  scene_max_len: 197
  n_discrete_classes: 26
  n_continuous_classes: 3
  add_pos: True
  text_model: 'bert-base-uncased'

output:
  model_dir: /data/digbose92/emotic_experiments/model_dir
  log_dir: /data/digbose92/emotic_experiments/log_dir